In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([5,6,7])

In [3]:
a*b

array([ 5, 12, 21])

In [4]:
a=np.array([[6,7,23,64,7],[66,69,45,44,12]])

In [5]:
print(a)

[[ 6  7 23 64  7]
 [66 69 45 44 12]]


In [6]:
#FOR DIMENSIONS
a.ndim

2

In [8]:
#type
a.dtype

dtype('int32')

In [10]:
x=np.array([[34,54,33,76,34],[76,34,65,39,69]])
print(x)

[[34 54 33 76 34]
 [76 34 65 39 69]]


In [12]:
#get specific element
x[1,4]

69

In [18]:
#get specific row and coloumn
x[0, :]

array([34, 54, 33, 76, 34])

In [19]:
x[:,3]

array([76, 39])

In [23]:
x[0, 1:3:2]

array([54])

In [25]:
x[0, 1:-1:2]

array([54, 76])

In [26]:
x[1,3]=34

In [27]:
x

array([[34, 54, 33, 76, 34],
       [76, 34, 65, 34, 69]])

In [30]:
b=np.array([[[3,4],[6,7]],[[5,6],[7,3]]])

In [31]:
b

array([[[3, 4],
        [6, 7]],

       [[5, 6],
        [7, 3]]])

In [32]:
b[1,0,1]

6