#### Data Normalisation

In [1]:
import pandas as pd
import torch
import numpy as np

In [3]:
df=pd.read_csv(r'C:\Users\HM\Downloads\Pandas+Course+Files\Datasets\cereal.csv')

In [4]:
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [5]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df = df.drop(columns=['mfr','type'])

In [14]:
df  # Convert the DataFrame to a PyTorch tensor

calories  protein  fat  sodium  fiber  carbo  sugars  potass  vitamins  \
0         70        4    1     130   10.0    5.0       6     280        25   
1        120        3    5      15    2.0    8.0       8     135         0   
2         70        4    1     260    9.0    7.0       5     320        25   
3         50        4    0     140   14.0    8.0       0     330        25   
4        110        2    2     200    1.0   14.0       8      -1        25   
..       ...      ...  ...     ...    ...    ...     ...     ...       ...   
72       110        2    1     250    0.0   21.0       3      60        25   
73       110        1    1     140    0.0   13.0      12      25        25   
74       100        3    1     230    3.0   17.0       3     115        25   
75       100        3    1     200    3.0   17.0       3     110        25   
76       110        2    1     200    1.0   16.0       8      60        25   

    shelf  weight  cups     rating  
0       3     1.0  0.33  68.402973  
1       3     1.0  1.00  33.983679  
2       3     1.0  0.33  59.425505  
3       3     1.0  0.50  93.704912  
4       3     1.0  0.75  34.384843  
..    ...     ...   ...        ...  
72      3     1.0  0.75  39.106174  
73      2     1.0  1.00  27.753301  
74      1     1.0  0.67  49.787445  
75      1     1.0  1.00  51.592193  
76      1     1.0  0.75  36.187559  

[77 rows x 13 columns]

In [15]:
data_tensor = torch.tensor(df.values)

In [16]:
print(data_tensor)

tensor([[ 70.0000,   4.0000,   1.0000,  ...,   1.0000,   0.3300,  68.4030],
        [120.0000,   3.0000,   5.0000,  ...,   1.0000,   1.0000,  33.9837],
        [ 70.0000,   4.0000,   1.0000,  ...,   1.0000,   0.3300,  59.4255],
        ...,
        [100.0000,   3.0000,   1.0000,  ...,   1.0000,   0.6700,  49.7874],
        [100.0000,   3.0000,   1.0000,  ...,   1.0000,   1.0000,  51.5922],
        [110.0000,   2.0000,   1.0000,  ...,   1.0000,   0.7500,  36.1876]],
       dtype=torch.float64)


In [17]:
type(data_tensor)

torch.Tensor

In [18]:
# Dim=0 means we are calculating the mean of each column
data_mean = torch.mean(data_tensor , dim=0)

In [19]:
data_mean            # Mean of each column

tensor([106.8831,   2.5455,   1.0130, 159.6753,   2.1519,  14.5974,   6.9221,
         96.0779,  28.2468,   2.2078,   1.0296,   0.8210,  42.6657],
       dtype=torch.float64)

### Variance

In [20]:
data_var = torch.var(data_tensor, dim=0)

In [21]:
data_var              # Variance of each column

tensor([3.7963e+02, 1.1986e+00, 1.0130e+00, 7.0279e+03, 5.6804e+00, 1.8309e+01,
        1.9757e+01, 5.0818e+03, 4.9919e+02, 6.9310e-01, 2.2643e-02, 5.4157e-02,
        1.9733e+02], dtype=torch.float64)

In [22]:
print(data_tensor)

tensor([[ 70.0000,   4.0000,   1.0000,  ...,   1.0000,   0.3300,  68.4030],
        [120.0000,   3.0000,   5.0000,  ...,   1.0000,   1.0000,  33.9837],
        [ 70.0000,   4.0000,   1.0000,  ...,   1.0000,   0.3300,  59.4255],
        ...,
        [100.0000,   3.0000,   1.0000,  ...,   1.0000,   0.6700,  49.7874],
        [100.0000,   3.0000,   1.0000,  ...,   1.0000,   1.0000,  51.5922],
        [110.0000,   2.0000,   1.0000,  ...,   1.0000,   0.7500,  36.1876]],
       dtype=torch.float64)


#### Normalization

In [23]:
data_norm = (data_tensor - data_mean)/torch.sqrt(data_var)   # Normalization formulae

In [24]:
data_norm                  # Normalized Data

tensor([[-1.8930,  1.3286, -0.0129,  ..., -0.1968, -2.1100,  1.8322],
        [ 0.6732,  0.4152,  3.9614,  ..., -0.1968,  0.7690, -0.6181],
        [-1.8930,  1.3286, -0.0129,  ..., -0.1968, -2.1100,  1.1931],
        ...,
        [-0.3533,  0.4152, -0.0129,  ..., -0.1968, -0.6490,  0.5070],
        [-0.3533,  0.4152, -0.0129,  ..., -0.1968,  0.7690,  0.6355],
        [ 0.1600, -0.4982, -0.0129,  ..., -0.1968, -0.3053, -0.4612]],
       dtype=torch.float64)