In [ ]:
import torch

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9223, 0.0566, 0.1969],
        [0.9635, 0.6341, 0.2818],
        [0.9869, 0.1334, 0.2089],
        [0.6506, 0.3988, 0.0268],
        [0.9706, 0.7878, 0.2534]])


In [13]:
y=torch.tensor([2.5,1.2], dtype=torch.int)
print(y)

tensor([2, 1], dtype=torch.int32)


In [14]:
y.dtype

torch.int32

In [17]:
a=torch.rand(2,2)        # all trailing underscore will do inplace func in tensor
b=torch.rand(2,2)
a
b
z=a+b
z

tensor([[1.4199, 1.3839],
        [1.1100, 1.0557]])

In [18]:
z=a*b
z

tensor([[0.5039, 0.4494],
        [0.2802, 0.2572]])

In [20]:
z=torch.mul(a,b)  # This will do same func as x*y will d

In [21]:
z

tensor([[0.5039, 0.4494],
        [0.2802, 0.2572]])

In [22]:
x=torch.rand(5,3)

In [23]:
x

tensor([[0.9420, 0.5308, 0.4629],
        [0.6666, 0.9394, 0.1097],
        [0.5202, 0.1546, 0.8784],
        [0.1141, 0.1895, 0.0410],
        [0.8760, 0.0668, 0.5700]])

In [26]:
print(x[:, 1])

tensor([0.5308, 0.9394, 0.1546, 0.1895, 0.0668])


In [27]:
print(x[3, :])

tensor([0.1141, 0.1895, 0.0410])


In [28]:
print(x[3,1].item())  #will provide us the actuall value, but only when there is one selected val

0.18951350450515747


In [29]:
import numpy as np

In [31]:
a=torch.ones(6)            #Converted torch to numpy
print(a)
b = a.numpy()
b

tensor([1., 1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [32]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [34]:
h=torch.from_numpy(b)      #tensor from numpy
h

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [35]:
h[3]=69

In [36]:
h

tensor([ 1.,  1.,  1., 69.,  1.], dtype=torch.float64)

In [41]:
c= torch.tensor(np.arange(0,15).reshape(5,3))  # indexing for 2d array

In [42]:
c

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [55]:
d=torch.zeros(3)

In [53]:
e=torch.rand([3], dtype = torch.float32) # This will be stored in d tensor

In [54]:
e

tensor([0.6670, 0.8986, 0.9907])

In [57]:
f=torch.ones(3)

In [58]:
h=f+e

In [59]:
h

tensor([1.6670, 1.8986, 1.9907])

In [60]:
torch.add(f,e,out=d)  #what we did here was, we stored the val of f+e into d,

tensor([1.6670, 1.8986, 1.9907])

In [61]:
d

tensor([1.6670, 1.8986, 1.9907])

In [62]:
torch.add(h,f).sum()

tensor(8.5562)